version: '1.0'
name: master-pipeline
displayName: pms-base_default
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - develop
    commitMessages:
      include:
        - ^(?!deploy:).*
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: '21'
        mavenVersion: 3.9.6
        commands:
          - mvn clean package -Dmaven.test.skip=true -s /root/workspace/futurecraftsmen/pms-base/customSettings.xml
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./pms-enterprise/pms-enterprise-service/target
              - ./pms-system/pms-system-service/target
        settings: []
        caches:
          - ~/.m2
        notify:
          - certificate: a1acb250-f193-013c-1bfe-422e76947380
            events:
              - fail
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: dingtalk
        strategy: {}
strategy:
  blocking: true
