version: '1.0'
name: pipeline-20240719-2
displayName: pms-base_开源认证
triggers:
  trigger: manual
  push:
    branches:
      precise:
        - develop
  schedule:
    - cron: '* 18 18 ? * 3 *'
stages:
  - name: stage-d928e4b4
    displayName: maven构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: '21'
        mavenVersion: 3.9.6
        commands:
          - mvn clean deploy -Dmaven.test.skip=true -s /root/workspace/futurecraftsmen/pms-base/customSettings.xml
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./pms-enterprise/pms-enterprise-service/target
              - ./pms-system/pms-system-service/target
        settings: []
        caches: []
        notify:
          - certificate: 665aaca0-25a2-013d-e10a-52c9b4a70496
            events:
              - success
              - fail
              - cancel
              - skip
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: dingtalk
        strategy:
          retry: '0'
strategy:
  blocking: true
