<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.futurecraftsmen.pms</groupId>
        <artifactId>pms-user-oriented</artifactId>
        <version>3.1.1.300</version>
    </parent>
    <packaging>jar</packaging>
    <artifactId>pms-user-oriented-bff</artifactId>
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-bff</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-enterprise-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-dm-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-system-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-dp-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-pas-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-technical-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-email-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-file-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-ow-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-right-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-dpa-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-message-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-user-oriented-api</artifactId>
            <version>3.1.1.300</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>itextpdf</artifactId>
        </dependency>

        <!-- 支持中文 -->
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>itext-asian</artifactId>
        </dependency>

        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-file-common</artifactId>
            <version>${project.version}</version>
        </dependency>

<!--        <dependency>-->
<!--            <groupId>com.alibaba.cloud.ai</groupId>-->
<!--            <artifactId>spring-ai-alibaba-starter</artifactId>-->
<!--        </dependency>-->


    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${build.plugins.plugin.version}</version>
                <configuration>
                    <mainClass>com.futurecraftsmen.pms.PmsServiceApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>