<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.futurecraftsmen.pms</groupId>
        <artifactId>pms-pas</artifactId>
        <version>3.1.1.300</version>
    </parent>
    <packaging>jar</packaging>
    <artifactId>pms-pas-service</artifactId>
    <dependencies>
        <!-- 测试接口暴漏HTTP端口设置，本地测试 -->
<!--        <dependency>-->
<!--            <groupId>com.futurecraftsmen.pms</groupId>-->
<!--            <artifactId>pms-bff</artifactId>-->
<!--            <version>${project.version}</version>-->
<!--        </dependency>-->
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-pas-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-dp-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-service</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-technical-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-enterprise-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-dm-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-file-document-sdk</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-right-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>itextpdf</artifactId>
        </dependency>
        <dependency>
            <groupId>com.itextpdf.tool</groupId>
            <artifactId>xmlworker</artifactId>
        </dependency>
        <!-- 支持中文 -->
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>itext-asian</artifactId>
        </dependency>
        <!-- 支持css样式渲染 -->
        <dependency>
            <groupId>org.xhtmlrenderer</groupId>
            <artifactId>flying-saucer-pdf-itext5</artifactId>
        </dependency>
        <!-- 转换html为标准xhtml包 -->
        <dependency>
            <groupId>net.sf.jtidy</groupId>
            <artifactId>jtidy</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.objenesis</groupId>
                    <artifactId>objenesis</artifactId>
                </exclusion>
            </exclusions>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
        </dependency>
        <dependency>
            <groupId>com.hankcs</groupId>
            <artifactId>hanlp</artifactId>
        </dependency>
        <dependency>
            <groupId>com.rnkrsoft.bopomofo4j</groupId>
            <artifactId>bopomofo4j</artifactId>
        </dependency>
        <dependency>
            <!-- this is needed or IntelliJ gives junit.jar or junit-platform-launcher:1.3.2 not found errors -->
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
        </dependency>
        <dependency>
            <groupId>ognl</groupId>
            <artifactId>ognl</artifactId>
            <version>3.3.5</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${build.plugins.plugin.version}</version>
                <configuration>
                    <mainClass>com.futurecraftsmen.pms.PmsServiceApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
                <inherited>false</inherited>
            </plugin>
        </plugins>
    </build>
</project>