<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.futurecraftsmen.pms</groupId>
        <artifactId>pms-base</artifactId>
        <version>3.1.1.300</version>
    </parent>
    <artifactId>pms-system</artifactId>
    <packaging>pom</packaging>
    <description>系统模块 - 全局服务注册, 全局动态配置参数</description>
    <modules>
        <module>pms-system-api</module>
        <module>pms-system-service</module>
    </modules>
</project>