# -*- coding: utf-8 -*-
[RUN]
RUN_CONF = {
           # 当前运行环境，环境配置内容见 environment.yaml
           "RUN_ENV" : "ERP_TEST",
           # 测试报告体现的执行用�?
           "USER": "Auto",
           # 测试报告执行/项目标题
           "PROJECT": "ErpTest",
           # 执行用例
           "CASE_PATH" : "获取报表数据集数�?yaml",
           # api 执行接口，webui 执行浏览器UI，mobileui 执行移动端UI，pcui 执行win桌面应用
           "TYPE" : "api",
           # 是否将测试报告发送邮件通知
           "is_sendmail": False,
           }

[CASE]
CASE_CONF = {
            # 多用例并发线程设置，�?时不使用并发模型
            "MAX_WORKERS_THREAD" : 1,
            # 用例失败重试次数，用例运行异常时进行重新运行，为1时只运行一�?
            "RETRY" : 1,
            # 优先级，运行用例等级数字小于该配置的用例
            "PRIORITY" : 3,
            "api": {
            # 是否使用host配置
            "is_host": False,
            # 是否开启api安全测试，开启后将只执行待安全测试类型的用例
            # sqlmap检测sql注入需要本地开启sqlmapapi服务，python 包安装目�?site-packages/sqlmapapi.py -s
            "is_safety": False
            },
            "web_ui": {
            # web浏览器，Chrome，Firefox，Ie
            "browser": "Chrome",
            "webdriver_path": "C:\\Users\\admin\\Downloads\\chromedriver-win64\\chromedriver-win64\\chromedriver.exe",
            "firefox_driver_path": "D:\\Program Files (x86)\\FX\\geckodriver.exe",
            "headless": False,
            },
            "pcui": {
            "deviceName": "WindowsPC",
            # 操作系统
            "platformName": "Windows",
            # 应用程序路径
            "app": r"",
            },
            # appPackage,appActivity 可以通过执行aapt dump badging 程序apk所在路径获�?当为空时，直接连接手机，界面为手机当前界�?
            # 手机进入开发者调试模式，通过adb devices 可以查看真机ID
            "mobileui": {
            # 真机或模拟器ID，默认为127.0.0.1:62001模拟器信�?
            "deviceName": "30c1c85c",
            # 操作系统
            "platformName": "Android",  # 操作系统
            # 程序包名 com.tencent.mm 微信�?
            "appPackage": "com.huiyi31.signin31",
            # 进入对应程序  com.huiyi31.qiandao.activity.SplashActivity
            "appActivity": "com.huiyi31.signin31.activity.BootActivity"
            }
            }

[EMAIL]
EMAIL_CONF = {
             # 发件人邮箱、密码，默认发送服务器�?163smtp 默认端口�?25
             "mail_host": "smtp.163.com",
             "mail_port":25,
             "mail_user": "gzy15565025655@163.com",
             "mail_pwd": "FUSF2PtsTegBEZYe",  # IMAP/SMTP授权�? qq smtp dhsyvckuurtdbdgg
             # 收件人邮箱列�?
             "recipients": ["957683840@qq.com"],
;              "recipients": ["957683840@qq.com"],
             # 抄送人邮件列表
             "cc_recipients": ["gzy15565025655@163.com"],
             # "cc_recipients": [],
             # 主题内容
             "content": """
             <p> Dear All: </p>
             <p> 下面是自动化测试报告的摘要信息，请相关测试人员和开发人员根据报告附件报错的错误信息进行问题定位�?</p>
             """
             }

