# windows 有中文注释时会有字符解析异常问题
# https://www.cnblogs.com/drewgg/p/13501096.html
# Configfile栏

# master.conf 配置说明
# 单机启动，或分布式启动
locustfile = core/locust_file.py
# 必填项，压测从用例取值，没有影响
host = http://127.0.0.1

# UI 界面下
web-host = 127.0.0.1
web-port = 8089

# 无 UI 界面，立即开始
headless = true
users = 10
hatch-rate= 1
run-time = 10s

# 起用分布式，主机配置
master = true
master-bind-host = 127.0.0.1
master-bind-port = 5557
# 无 UI 界面，分布式，指定从机数量，达到后开始压测
expect-workers = 8

# 日志
logfile = logs/locust_master.log
loglevel = INFO


# worker.conf 配置说明
# 起用分布式，从机配置，主要配置一定与主机一致
locustfile = core/locust_file.py

# 从机与主机交互的主机IP
worker = true
master-host = 127.0.0.1
master-port = 5557



