locustfile = /altest/autotest_elegant/core/locust_file.py
host = http://127.0.0.1

web-host = 0.0.0.0
web-port = 8089

; headless = true
; users = 50
; hatch-rate= 10
; run-time = 60s

master = true
master-bind-host = 127.0.0.1
master-bind-port = 5557
; expect-workers = 8

loglevel = INFO


