<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.futurecraftsmen.pms</groupId>
        <artifactId>pms</artifactId>
        <version>3.1.1.300</version>
    </parent>
    <artifactId>pms-core</artifactId>
    <version>3.1.1.300</version>
    <packaging>pom</packaging>
    <description>无代码 process management system 平台</description>
    <modules>
        <module>pms-dm</module>
        <module>pms-dp</module>
        <module>pms-dpa</module>
        <module>pms-right</module>
    </modules>
</project>