version: '1.0'
name: pipeline-20240718
displayName: pms_deploy
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - develop
    commitMessages:
      include:
        - ^deploy:.*
stages:
  - name: stage-d616e05c
    displayName: maven构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: '21'
        mavenVersion: 3.9.6
        commands:
          - mvn clean deploy -Dmaven.test.skip=true -s /root/workspace/futurecraftsmen/pms/customSettings.xml
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./pms-common/target
              - ./pms-framework/pms-api/target
              - ./pms-framework/pms-bff/target
              - ./pms-framework/pms-service/target
              - ./pms-framework/pms-starter/target
        settings: []
        caches: []
        notify:
          - certificate: a1acb250-f193-013c-1bfe-422e76947380
            events:
              - fail
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: dingtalk
        strategy:
          retry: '0'
strategy:
  blocking: true
