<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) Zhongzao Software Co. LTD 2022-2062 All rights reserved
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.futurecraftsmen.pms</groupId>
        <artifactId>pms-dm</artifactId>
        <version>3.1.1.300</version>
    </parent>
    <artifactId>pms-dm-service</artifactId>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <!--生成自定义配置的元数据信息-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.belerweb</groupId>
            <artifactId>pinyin4j</artifactId>
            <version>2.5.1</version>
        </dependency>


        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-service</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.objenesis</groupId>
                    <artifactId>objenesis</artifactId>
                </exclusion>
            </exclusions>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-dm-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-enterprise-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.aerie.forest</groupId>
            <artifactId>forest-signature</artifactId>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-file-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-file-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.futurecraftsmen.pms</groupId>
            <artifactId>pms-right-api</artifactId>
            <version>3.1.1.300</version>
            <scope>compile</scope>
        </dependency>
        <!-- 测试接口暴漏HTTP端口设置，本地测试 -->
<!--        <dependency>-->
<!--            <groupId>com.futurecraftsmen.pms</groupId>-->
<!--            <artifactId>pms-bff</artifactId>-->
<!--            <version>${project.version}</version>-->
<!--        </dependency>-->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dashscope-sdk-java</artifactId>
            <!-- 请将 'the-latest-version' 替换为最新版本号：https://mvnrepository.com/artifact/com.alibaba/dashscope-sdk-java -->
            <version>2.20.7</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${build.plugins.plugin.version}</version>
                <configuration>
                    <mainClass>com.futurecraftsmen.pms.PmsServiceApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>