case_code: EnterpriseMenuConfigController
case_name: EnterpriseMenuConfigController接口测试
priority: 2
steps:
- headers: $generate_token(api_host)
  host: $get_host(ERP_TEST,api_host)
  method: GET
  params: {}
  path: /detail
  response_assert:
    response_assert_data: 接口调用成功
    status_code_assert: 200
  step_name: 企业功能职责
