case_code: ProductPartTypeController
case_name: ProductPartTypeController接口测试
priority: 2
steps:
- headers: $generate_token(api_host)
  host: $get_host(ERP_TEST,api_host)
  method: GET
  params: {}
  path: getProductPartTypeTree
  response_assert:
    response_assert_data: 接口调用成功
    status_code_assert: 200
  step_name: 技术部-产品零件分类接口 控制器
