case_code: ProductPartQualityItemsController
case_name: ProductPartQualityItemsController接口测试
priority: 2
steps:
- data:
    ProductPartQualityItemsRpcRequest: {}
  headers: $generate_token(api_host)
  host: $get_host(ERP_TEST,api_host)
  method: POST
  path: getProductPartQualityItemsList
  response_assert:
    response_assert_data: 接口调用成功
    status_code_assert: 200
  step_name: 产品零件质检检验项 控制器
