case_code: ProductPartProcedureController
case_name: ProductPartProcedureController接口测试
priority: 2
steps:
- data:
    ProductPartProcedureRpcRequest: {}
  headers: $generate_token(api_host)
  host: $get_host(ERP_TEST,api_host)
  method: POST
  path: productPartProcedurePageList
  response_assert:
    response_assert_data: 接口调用成功
    status_code_assert: 200
  step_name: 产品零件工序 控制器
